/* eslint-disable */

const languages = {
  en: {
    title: '🧹 Dev Starter Cleanup Process',
    selectLanguage: 'Which language would you like to continue with?',
    options: {
      english: 'English',
      turkish: 'Turkish',
      german: 'German'
    },
    confirmDeleteDirectories: 'Do you want to start deleting directories (with their contents)?',
    checkingDirectories: 'Checking directories...',
    existingDirectories: 'Existing directories:',
    missingDirectories: 'Missing directories:',
    confirmDelete: 'Are you sure you want to delete the existing directories?',
    willDelete: 'Will be deleted:',
    willSkip: 'Will be skipped (not found):',
    confirmDeleteFiles: 'Do you want to start deleting files?',
    checkingFiles: 'Checking files...',
    existingFiles: 'Existing files:',
    missingFiles: 'Missing files:',
    confirmEditFiles: 'Do you want to start editing files?',
    editingFiles: 'Editing files...',
    enterAppName: 'Enter new application name:',
    enterProjectName: 'Enter new project name:',
    success: 'Cleanup process completed successfully!',
    restartInfo: 'To restart your project: npm run dev',
    error: 'An error occurred during cleanup:',
    yes: 'Yes',
    no: 'No',
    cancelled: 'Operation cancelled by user.',
    keepCurrentAppNameInfo: 'Press ENTER to keep the current app name.',
    currentAppName: 'Current app name: ',
    emptyAppNameWarning: 'App name cannot be empty!',
    keepCurrentProjectNameInfo: 'Press ENTER to keep the current project name.',
    currentProjectName: 'Current project name: ',
    projectNameFormatInfo: 'Project name must be lowercase and hyphenated (e.g. dev-starter).',
    emptyProjectNameWarning: 'Project name cannot be empty!',
    invalidProjectNameWarning: 'Project name must contain only lowercase letters, numbers, and hyphens!'
  },
  tr: {
    title: '🧹 Dev Starter Temizlik İşlemi',
    selectLanguage: 'İşlemlere hangi dilde devam etmek istiyorsunuz?',
    options: {
      english: 'İngilizce',
      turkish: 'Türkçe',
      german: 'Almanca'
    },
    confirmDeleteDirectories: 'Klasörleri (içerikleri ile beraber) silme işlemini başlatmak istiyor musunuz?',
    checkingDirectories: 'Klasörler kontrol ediliyor...',
    existingDirectories: 'Mevcut klasörler:',
    missingDirectories: 'Bulunamayan klasörler:',
    confirmDelete: 'Mevcut klasörleri silmek istediğinizden emin misiniz?',
    willDelete: 'Silinecek olanlar:',
    willSkip: 'Atlanacak olanlar (bulunamadı):',
    confirmDeleteFiles: 'Dosyaları silme işlemini başlatmak istiyor musunuz?',
    checkingFiles: 'Dosyalar kontrol ediliyor...',
    existingFiles: 'Mevcut dosyalar:',
    missingFiles: 'Bulunamayan dosyalar:',
    confirmEditFiles: 'Dosyaları düzenleme işlemini başlatmak istiyor musunuz?',
    editingFiles: 'Dosyalar düzenleniyor...',
    enterAppName: 'Yeni uygulama adını girin:',
    enterProjectName: 'Yeni proje adını girin:',
    success: 'Temizlik işlemi başarıyla tamamlandı!',
    restartInfo: 'Projenizi yeniden başlatmak için: npm run dev',
    error: 'Temizlik işlemi sırasında hata oluştu:',
    yes: 'Evet',
    no: 'Hayır',
    cancelled: 'İşlem kullanıcı tarafından iptal edildi.',
    keepCurrentAppNameInfo: 'Mevcut uygulama adını korumak için ENTER basabilirsiniz.',
    currentAppName: 'Mevcut uygulama adı: ',
    emptyAppNameWarning: 'Uygulama adı boş olamaz!',
    keepCurrentProjectNameInfo: 'Mevcut proje adını korumak için ENTER basabilirsiniz.',
    currentProjectName: 'Mevcut proje adı: ',
    projectNameFormatInfo: 'Proje adı küçük harf ve tireli olmalı (ör: dev-starter).',
    emptyProjectNameWarning: 'Proje adı boş olamaz!',
    invalidProjectNameWarning: 'Proje adı sadece küçük harf, rakam ve tire içermelidir!'
  },
  de: {
    title: '🧹 Dev Starter Bereinigungsprozess',
    selectLanguage: 'In welcher Sprache möchten Sie fortfahren?',
    options: {
      english: 'Englisch',
      turkish: 'Türkisch',
      german: 'Deutsch'
    },
    confirmDeleteDirectories: 'Möchten Sie mit dem Löschen von Verzeichnissen (mit Inhalten) beginnen?',
    checkingDirectories: 'Verzeichnisse werden überprüft...',
    existingDirectories: 'Vorhandene Verzeichnisse:',
    missingDirectories: 'Fehlende Verzeichnisse:',
    confirmDelete: 'Sind Sie sicher, dass Sie die vorhandenen Verzeichnisse löschen möchten?',
    willDelete: 'Wird gelöscht:',
    willSkip: 'Wird übersprungen (nicht gefunden):',
    confirmDeleteFiles: 'Möchten Sie mit dem Löschen von Dateien beginnen?',
    checkingFiles: 'Dateien werden überprüft...',
    existingFiles: 'Vorhandene Dateien:',
    missingFiles: 'Fehlende Dateien:',
    confirmEditFiles: 'Möchten Sie mit dem Bearbeiten von Dateien beginnen?',
    editingFiles: 'Dateien werden bearbeitet...',
    enterAppName: 'Geben Sie den neuen Anwendungsnamen ein:',
    enterProjectName: 'Geben Sie den neuen Projektnamen ein:',
    success: 'Bereinigungsprozess erfolgreich abgeschlossen!',
    restartInfo: 'Um Ihr Projekt neu zu starten: npm run dev',
    error: 'Während der Bereinigung ist ein Fehler aufgetreten:',
    yes: 'Ja',
    no: 'Nein',
    cancelled: 'Vorgang vom Benutzer abgebrochen.',
    keepCurrentAppNameInfo: 'Drücken Sie ENTER, um den aktuellen App-Namen zu behalten.',
    currentAppName: 'Aktueller App-Name: ',
    emptyAppNameWarning: 'App-Name darf nicht leer sein!',
    keepCurrentProjectNameInfo: 'Drücken Sie ENTER, um den aktuellen Projektnamen zu behalten.',
    currentProjectName: 'Aktueller Projektname: ',
    projectNameFormatInfo: 'Projektname muss klein geschrieben und mit Bindestrich versehen sein (z.B. dev-starter).',
    emptyProjectNameWarning: 'Projektname darf nicht leer sein!',
    invalidProjectNameWarning: 'Projektname darf nur Kleinbuchstaben, Zahlen und Bindestriche enthalten!'
  }
};

module.exports = languages; 